export const FETCH_ALL_RECIPES_START = 'FETCH_ALL_RECIPES_START';
export const FETCH_ALL_RECIPES_FAIL = 'FETCH_ALL_RECIPES_FAIL';
export const FETCH_ALL_RECIPES_SUCCESS = 'FETCH_ALL_RECIPES_SUCCESS';

export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';
export const FETCH_RECIPE_FAIL = 'FETCH_RECIPE_FAIL';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';

export const ADD_RECIPE_START = 'ADD_RECIPE_START';
export const ADD_RECIPE_FAIL = 'ADD_RECIPE_FAIL';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';

export const UPDATE_RECIPE_START = 'UPDATE_RECIPE_START';
export const UPDATE_RECIPE_FAIL = 'UPDATE_RECIPE_FAIL';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';

export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
