export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';

export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';
export const FETCH_RECIPE_FAIL = 'FETCH_RECIPE_FAIL';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';

export const SAVE_RECIPE_START = 'SAVE_RECIPE_START';
export const SAVE_RECIPE_FAIL = 'SAVE_RECIPE_FAIL';
export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS';

export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
